	.align 2
voicegroup_bw_e4_gm:: @ improved BW Elite Four (GM-mapped onto vg274/Drum1 samples)
	voice_keysplit voicegroupInst1, KeySplitTable90	@ piano
	voice_keysplit_all voicegroupDrum1	@ drum kit (GM-mapped notes)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_directsound 60, 0, DirectSoundWaveData_bw_glockenspiel_c5, 255, 249, 0, 208	@ glockenspiel
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_keysplit voicegroup249, KeySplitTable32	@ distortion guitar
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_keysplit voicegroup253, KeySplitTable43	@ fingered bass
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_keysplit voicegroup254, KeySplitTable44	@ synth bass
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_keysplit voicegroup260, KeySplitTable40	@ timpani
	voice_keysplit voicegroup255, KeySplitTable45	@ strings
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_directsound 60, 0, DirectSoundWaveData_bw_orch_hit_c5, 255, 250, 2, 208	@ orchestra hit
	voice_keysplit voicegroup261, KeySplitTable39	@ trumpet
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_keysplit voicegroupInst34, KeySplitTable22	@ tuba
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_keysplit voicegroup264, KeySplitTable50	@ french horn
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_keysplit voicegroup251, KeySplitTable41	@ clean guitar
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 242, 25, 0	@ GB square lead
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 242, 25, 0	@ GB square lead
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 242, 25, 0	@ GB square lead
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 242, 25, 0	@ GB square lead
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
