gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is BIRCH.\p"
	.string "But everyone calls me the POKéMON\n"
	.string "PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "We humans live alongside POKéMON,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about POKéMON.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding POKéMON.\p"
	.string "To unravel POKéMON mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_Nuzlocke::
	.string "Allow me to explain the different\n"
	.string "difficulty options...\p"
	.string "Black Pearl Emerald has two\n"
	.string "difficulty modes...\l"
	.string "STANDARD MODE and NUZLOCKE MODE.\p"
	.string "Both modes include a Candy Jar,\n"
	.string "so level grinding is optional.\p"
	.string "STANDARD MODE RULES:\p"
	.string "STANDARD MODE enforces a level cap at\n"
	.string "each gym split. It is intended for\l"
	.string "Beginner to Intermediate players.\p"
	.string "Pokemon catchrates will be normal.\p"
	.string "Players will earn and spend\n"
	.string "money as normal.\p"
	.string "Players can catch as many Pokemon\n"
	.string "as they want, and will always be able\l"
	.string "to revive fainted Pokemon.\p"
	.string "NUZLOCKE MODE RULES:\p"
	.string "NUZLOCKE MODE enforces a level cap at\n"
	.string "each gym split. It is intended for\l"
	.string "Experienced Pokemon players.\p"
	.string "All Pokemon catchrates will be 100.\p"
	.string "Players will be given unlimited money,\n"
	.string "meaning, money grinding is not required\p"
	.string "Players can only catch ONE Pokemon per\n"
	.string "area. Once a Pokemon faints, it will\l"
	.string "NOT be able to be revived!\p"
	.string "With that in mind...\p"
	.string "Would you like to play in\n"
	.string "NUZLOCKE (EXPERT) MODE?$"

gText_Birch_Randomizer::
	.string "One more thing…\p"
	.string "You can RANDOMIZE your adventure:\n"
	.string "the POKéMON you meet, the trainers\l"
	.string "you battle, and much more.\p"
	.string "A SEED CODE lets your friends play\n"
	.string "the very same randomized game.\p"
	.string "Your choice can't be changed later.\n"
	.string "Would you like to randomize?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
