gText_HowMayIServeYou::
	.string "Welcome!\p"
	.string "How may I serve you?$"

gText_PleaseComeAgain::
	.string "Please come again!$"

gText_PlayerWhatCanIDoForYou::
	.string "{PLAYER}{STRING 5}, welcome!\p"
	.string "What can I do for you?$"

gText_Beans_HowMayIServeYou::
	.string "Welcome to The Beans Shop!\p"
	.string "My name is Mason, but you\n"
	.string "can just call me Beans!\p"
	.string "I'm no regular shopkeeper...\p"
	.string "My inventory expands as you\n"
	.string "earn more Gym Badges!\p"
	.string "How may I serve you?$"