gTrickHouse_Mechadoll_Oddish::
	.string "THUNDERBOLT$"

gTrickHouse_Mechadoll_Poochyena::
	.string "HYDRO PUMP$"

gTrickHouse_Mechadoll_Taillow::
	.string "SUCKER PUNCH$"

gTrickHouse_Mechadoll_Azurill::
	.string "PRESSURE$"

gTrickHouse_Mechadoll_Lotad::
	.string "TERAVOLT$"

gTrickHouse_Mechadoll_Wingull::
	.string "TURBOBLAZE$"

gTrickHouse_Mechadoll_Dustox::
	.string "30$"

gTrickHouse_Mechadoll_Zubat::
	.string "35$"

gTrickHouse_Mechadoll_Nincada::
	.string "25$"

gTrickHouse_Mechadoll_Ralts::
	.string "1$"

gTrickHouse_Mechadoll_Zigzagoon::
	.string "2$"

gTrickHouse_Mechadoll_Slakoth::
	.string "0$"

gTrickHouse_Mechadoll_Poochyena2::
	.string "1$"

gTrickHouse_Mechadoll_Shroomish::
	.string "3$"

gTrickHouse_Mechadoll_Zigzagoon2::
	.string "2$"

gTrickHouse_Mechadoll_Poochyena3::
	.string "INSTRUCT$"

gTrickHouse_Mechadoll_Zubat2::
	.string "TORMENT$"

gTrickHouse_Mechadoll_Carvanha::
	.string "TAUNT$"

gTrickHouse_Mechadoll_BurnHeal::
	.string "MAGNEZONE$"

gTrickHouse_Mechadoll_HarborMail::
	.string "JIGGLYBUFF$"

gTrickHouse_Mechadoll_SamePrice::
	.string "DELIBIRD$"

gTrickHouse_Mechadoll_60Yen::
	.string "MOUNT CORONET$"

gTrickHouse_Mechadoll_55Yen::
	.string "WHITE OUT CAVES$"

gTrickHouse_Mechadoll_Nothing::
	.string "WAYWARD CAVE$"

gTrickHouse_Mechadoll_CostMore::
	.string "UNIQUE$"

gTrickHouse_Mechadoll_CostLess::
	.string "ANTIQUE$"

gTrickHouse_Mechadoll_SamePrice2::
	.string "PERFECT$"

gTrickHouse_Mechadoll_Male::
	.string "SLOW START$"

gTrickHouse_Mechadoll_Female::
	.string "SPEED BOOST$"

gTrickHouse_Mechadoll_Neither::
	.string "STEAM ENGINE$"

gTrickHouse_Mechadoll_ElderlyMen::
	.string "Dudunsparce$"

gTrickHouse_Mechadoll_ElderlyLadies::
	.string "Dunundsparce$"

gTrickHouse_Mechadoll_SameNumber::
	.string "Dondunsparce$"

gTrickHouse_Mechadoll_None::
	.string "250$"

gTrickHouse_Mechadoll_One::
	.string "255$"

gTrickHouse_Mechadoll_Two::
	.string "245$"

gTrickHouse_Mechadoll_Two2::
	.string "CELL BATTERY$"

gTrickHouse_Mechadoll_Three::
	.string "SHOCK DRIVE$"

gTrickHouse_Mechadoll_Four::
	.string "ZAP DISK$"

gTrickHouse_Mechadoll_Six::
	.string "NIMBASA$"

gTrickHouse_Mechadoll_Seven::
	.string "DRIFTVEIL$"

gTrickHouse_Mechadoll_Eight::
	.string "NACRENE$"

gTrickHouse_Mechadoll_Six2::
	.string "SILVALLY$"

gTrickHouse_Mechadoll_Seven2::
	.string "ARCEUS$"

gTrickHouse_Mechadoll_Eight2::
	.string "KELDEO$"
