gText_HowMayIServeYou::
	.string "Welcome!\p"
	.string "How may I serve you?$"

gText_PleaseComeAgain::
	.string "Please come again!$"

gText_PlayerWhatCanIDoForYou::
	.string "{PLAYER}{KUN}, welcome!\p"
	.string "What can I do for you?$"

gText_Beans_HowMayIServeYou::
	.string "Welcome to The Beans Shop!\p"
	.string "My name is Mason, but you\n"
	.string "can just call me Beans!\p"
	.string "I'm no regular shopkeeper...\p"
	.string "My inventory expands as you\n"
	.string "earn more Gym Badges!\p"
	.string "How may I serve you?$"

Pokemart_DefaultItemList::
	.2byte ITEM_ULTRA_BALL
	.2byte ITEM_HYPER_POTION
	.2byte ITEM_MAX_POTION
	.2byte ITEM_FULL_RESTORE
	.2byte ITEM_FULL_HEAL
	.2byte ITEM_REVIVE
	.2byte ITEM_MAX_REPEL
	pokemartlistend
