#!/usr/bin/env python3
"""
gen_lua_tables.py — Generate Lua lookup tables from BPE Emerald C headers.

Outputs three Lua table literals:
  - SPECIES: id -> name string
  - MOVES:   id -> name string
  - MAPS:    (mapGroup << 8 | mapNum) -> name string

Run from the pokeemerald-expansion root:
  py BPETools/gen_lua_tables.py > BPETools/lua_tables.lua
Or used by mgba_server.lua via embedded output.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent  # pokeemerald-expansion/


def title(name: str) -> str:
    """Convert SCREAMING_SNAKE to Title Case label, e.g. SPECIES_BULBASAUR -> Bulbasaur."""
    parts = name.split("_", 1)
    if len(parts) < 2:
        return name.title()
    label = parts[1]
    return label.replace("_", " ").title()


def parse_species(path: Path) -> dict[int, str]:
    """Parse #define SPECIES_NAME value from species.h, skipping aliases/guards."""
    species = {}
    seen_names: set[str] = set()
    pattern = re.compile(r"^#define\s+(SPECIES_\w+)\s+(\d+)")
    with open(path, encoding="utf-8") as f:
        for line in f:
            m = pattern.match(line.strip())
            if not m:
                continue
            name, val = m.group(1), int(m.group(2))
            # Skip if this value is already mapped (keep first occurrence = canonical)
            if val in species:
                continue
            # Skip SPECIES_NONE and form aliases that point to same id
            if name in seen_names:
                continue
            seen_names.add(name)
            label = title(name)
            species[val] = label
    return species


def parse_moves(path: Path) -> dict[int, str]:
    """Parse enum Move { MOVE_NAME = value, ... } from moves.h."""
    moves = {}
    pattern = re.compile(r"\b(MOVE_\w+)\s*=\s*(\d+)")
    with open(path, encoding="utf-8") as f:
        content = f.read()
    for m in pattern.finditer(content):
        name, val = m.group(1), int(m.group(2))
        if val in moves:
            continue  # keep first (canonical)
        label = title(name)
        moves[val] = label
    return moves


def parse_maps(path: Path) -> dict[int, str]:
    """Parse MAP_NAME = (mapNum | (mapGroup << 8)) enum entries from map_groups.h."""
    maps = {}
    # Match: MAP_SOMETHING = (N | (G << 8))  or  MAP_SOMETHING = (N | (G<<8))
    pattern = re.compile(r"\b(MAP_\w+)\s*=\s*\(\s*(\d+)\s*\|\s*\(\s*(\d+)\s*<<\s*8\s*\)\s*\)")
    with open(path, encoding="utf-8") as f:
        content = f.read()
    for m in pattern.finditer(content):
        name = m.group(1)
        map_num = int(m.group(2))
        map_group = int(m.group(3))
        key = (map_group << 8) | map_num
        if key in maps:
            continue
        label = name[4:].replace("_", " ").title()  # strip "MAP_" prefix
        maps[key] = label
    return maps


def lua_table(name: str, data: dict[int, str]) -> str:
    """Render a Lua table literal: local NAME = { [k] = "v", ... }"""
    lines = [f"local {name} = {{"]
    for key in sorted(data):
        val = data[key].replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'  [{key}] = "{val}",')
    lines.append("}")
    return "\n".join(lines)


def main():
    species_path = ROOT / "include" / "constants" / "species.h"
    moves_path   = ROOT / "include" / "constants" / "moves.h"
    maps_path    = ROOT / "include" / "constants" / "map_groups.h"

    for p in (species_path, moves_path, maps_path):
        if not p.exists():
            print(f"ERROR: {p} not found", file=sys.stderr)
            sys.exit(1)

    species = parse_species(species_path)
    moves   = parse_moves(moves_path)
    maps    = parse_maps(maps_path)

    print(f"-- AUTO-GENERATED by gen_lua_tables.py -- do not edit manually")
    print(f"-- Species: {len(species)} entries, Moves: {len(moves)} entries, Maps: {len(maps)} entries")
    print()
    print(lua_table("SPECIES", species))
    print()
    print(lua_table("MOVES", moves))
    print()
    print(lua_table("MAPS", maps))
    print()
    print("return { SPECIES = SPECIES, MOVES = MOVES, MAPS = MAPS }")


if __name__ == "__main__":
    main()
