"""Render the release label as GBA-native sprite tiles; no image dependencies."""
import argparse
import json
from pathlib import Path
from release_lib import ROOT, label, version

# Five-column, seven-row bitmap glyphs. The build emits native 4bpp sprite data.
GLYPHS = {
    "0":"01110/10001/10011/10101/11001/10001/01110", "1":"00100/01100/00100/00100/00100/00100/01110",
    "2":"01110/10001/00001/00010/00100/01000/11111", "3":"11110/00001/00001/01110/00001/00001/11110",
    "4":"00010/00110/01010/10010/11111/00010/00010", "5":"11111/10000/10000/11110/00001/00001/11110",
    "6":"01110/10000/10000/11110/10001/10001/01110", "7":"11111/00001/00010/00100/01000/01000/01000",
    "8":"01110/10001/10001/01110/10001/10001/01110", "9":"01110/10001/10001/01111/00001/00001/01110",
    "A":"01110/10001/10001/11111/10001/10001/10001", "B":"11110/10001/10001/11110/10001/10001/11110",
    "C":"01111/10000/10000/10000/10000/10000/01111", "D":"11110/10001/10001/10001/10001/10001/11110",
    "E":"11111/10000/10000/11110/10000/10000/11111", "F":"11111/10000/10000/11110/10000/10000/10000",
    "G":"01111/10000/10000/10111/10001/10001/01111", "H":"10001/10001/10001/11111/10001/10001/10001",
    "I":"01110/00100/00100/00100/00100/00100/01110", "J":"00111/00010/00010/00010/00010/10010/01100",
    "K":"10001/10010/10100/11000/10100/10010/10001", "L":"10000/10000/10000/10000/10000/10000/11111",
    "M":"10001/11011/10101/10101/10001/10001/10001", "N":"10001/11001/11001/10101/10011/10011/10001",
    "O":"01110/10001/10001/10001/10001/10001/01110", "P":"11110/10001/10001/11110/10000/10000/10000",
    "Q":"01110/10001/10001/10001/10101/10010/01101", "R":"11110/10001/10001/11110/10100/10010/10001",
    "S":"01111/10000/10000/01110/00001/00001/11110", "T":"11111/00100/00100/00100/00100/00100/00100",
    "U":"10001/10001/10001/10001/10001/10001/01110", "V":"10001/10001/10001/10001/10001/01010/00100",
    "W":"10001/10001/10001/10101/10101/10101/01010", "X":"10001/10001/01010/00100/01010/10001/10001",
    "Y":"10001/10001/01010/00100/00100/00100/00100", "Z":"11111/00001/00010/00100/01000/10000/11111",
    ".":"00000/00000/00000/00000/00000/00100/00100", "-":"00000/00000/00000/11111/00000/00000/00000",
    " ":"00000/00000/00000/00000/00000/00000/00000",
}


def generate(config, output):
    release = version(json.loads(Path(config).read_text())["version"])
    text = label(release).upper()
    pixels = [[0] * 160 for _ in range(8)]
    left = (160 - len(text) * 6 + 1) // 2
    for i, char in enumerate(text):
        for y, row in enumerate(GLYPHS[char].split("/")):
            for x, bit in enumerate(row):
                pixels[y][left + i * 6 + x] = int(bit)
    data = []
    for tile in range(20):
        for row in pixels:
            for x in range(tile * 8, tile * 8 + 8, 2):
                data.append(row[x] | row[x + 1] << 4)
    content = '// Generated by BPETools/generate_release_header.py.\n'
    content += '#define BPE_RELEASE_MARKER "BPE_RELEASE:' + release + '"\n'
    content += 'static const u8 sBpeReleaseTiles[] = {\n'
    content += '\n'.join('    ' + ', '.join(f'0x{x:02x}' for x in data[i:i+16]) + ',' for i in range(0, len(data), 16))
    content += '\n};\n'
    output = Path(output)
    output.parent.mkdir(parents=True, exist_ok=True)
    if not output.exists() or output.read_text() != content:
        output.write_text(content, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=ROOT / "BPE_VERSION.json")
    parser.add_argument("--output", type=Path, default=ROOT / "include/generated/bpe_release.h")
    args = parser.parse_args()
    generate(args.config, args.output)
