"""Render the release label as GBA-native sprite tiles; no image dependencies."""
import argparse
import json
from pathlib import Path
from release_lib import ROOT, label, version

# Compact three-column, five-row glyphs for the bottom-left release label.
GLYPHS = {
    "0":"111/101/101/101/111", "1":"010/110/010/010/111",
    "2":"111/001/111/100/111", "3":"111/001/111/001/111",
    "4":"101/101/111/001/001", "5":"111/100/111/001/111",
    "6":"111/100/111/101/111", "7":"111/001/010/010/010",
    "8":"111/101/111/101/111", "9":"111/101/111/001/111",
    "A":"010/101/111/101/101", "B":"110/101/110/101/110",
    "C":"111/100/100/100/111", "D":"110/101/101/101/110",
    "E":"111/100/110/100/111", "F":"111/100/110/100/100",
    "G":"111/100/101/101/111", "H":"101/101/111/101/101",
    "I":"111/010/010/010/111", "J":"001/001/001/101/111",
    "K":"101/101/110/101/101", "L":"100/100/100/100/111",
    "M":"101/111/111/101/101", "N":"101/111/111/111/101",
    "O":"111/101/101/101/111", "P":"111/101/111/100/100",
    "Q":"111/101/101/111/001", "R":"110/101/110/101/101",
    "S":"111/100/111/001/111", "T":"111/010/010/010/010",
    "U":"101/101/101/101/111", "V":"101/101/101/101/010",
    "W":"101/101/111/111/101", "X":"101/101/010/101/101",
    "Y":"101/101/010/010/010", "Z":"111/001/010/100/111",
    ".":"000/000/000/000/010", "-":"000/000/111/000/000",
    " ":"000/000/000/000/000",
}


def generate(config, output):
    release = version(json.loads(Path(config).read_text())["version"])
    text = label(release).upper()
    pixels = [[0] * 160 for _ in range(8)]
    points = []
    for i, char in enumerate(text):
        for y, row in enumerate(GLYPHS[char].split("/")):
            for x, bit in enumerate(row):
                if bit == "1":
                    points.append((i * 4 + x, y + 1))
    for x, y in points:
        pixels[y + 1][x + 1] = 2  # dark shadow keeps the small text readable
    for x, y in points:
        pixels[y][x] = 1
    data = []
    for tile in range(20):
        for row in pixels:
            for x in range(tile * 8, tile * 8 + 8, 2):
                data.append(row[x] | row[x + 1] << 4)
    content = '// Generated by BPETools/generate_release_header.py.\n'
    content += '#define BPE_RELEASE_MARKER "BPE_RELEASE:' + release + '"\n'
    content += 'static const u8 sBpeReleaseTiles[] = {\n'
    content += '\n'.join('    ' + ', '.join(f'0x{x:02x}' for x in data[i:i+16]) + ',' for i in range(0, len(data), 16))
    content += '\n};\n'
    output = Path(output)
    output.parent.mkdir(parents=True, exist_ok=True)
    if not output.exists() or output.read_text() != content:
        output.write_text(content, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=ROOT / "BPE_VERSION.json")
    parser.add_argument("--output", type=Path, default=ROOT / "include/generated/bpe_release.h")
    args = parser.parse_args()
    generate(args.config, args.output)
